name: Test PETSc on GitHub with mumps

on:
  push:
    branches: [main]
    # paths:
    #   - patches/*

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: addnab/docker-run-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ghcr.io
          image: ghcr.io/carlosal1015/aur/mumps:latest
          options: |
            -v ${{github.workspace}}:/work
          shell: bash
          run: |
            sudo pacman -Syuq --needed --noconfirm
            sudo pacman -S git --noconfirm