name: PETSc (real scalar)

on:
  push:
    branches: [main]
    # paths:
    #   - patches/*

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: addnab/docker-run-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ghcr.io
          image: ghcr.io/carlosal1015/aur/petsc-complex:latest
          options: |
            -v ${{github.workspace}}:/work
          shell: bash
          run: |
            sudo pacman -Syuq --needed --noconfirm >/dev/null 2>&1
            cd
            curl -O https://petsc.org/release/petsc4py/_static/poisson2d.py
            mpiexec -n 2 python poisson2d.py -view_sol -view_mat -n 10 -ksp_type preonly
            # https://groups.google.com/g/moose-users/c/PSO8iNMZ3Qg
            # https://stackoverflow.com/a/26535447/9302545
            python poisson2d.py -view_sol -view_mat -n 10 -ksp_type preonly -pc_type lu