name: PETSc (real scalar)

on:
  push:
    branches: [main]
    paths:
      - patches/*

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: addnab/docker-run-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ghcr.io
          image: ghcr.io/carlosal1015/aur/petsc:latest
          options: |
            -v ${{github.workspace}}:/work
          shell: bash
          run: |
            sudo pacman -Syuq --needed --noconfirm >/dev/null 2>&1
            sudo pacman -S git --noconfirm >/dev/null 2>&1
            cd
            git clone https://aur.archlinux.org/petsc.git
            cd petsc
            makepkg --noconfirm --nocheck -s
            pushd /tmp/makepkg/petsc/src/petsc-3.21.0/src/snes/tutorials
            ls -l
            chmod +x ex19
            ls -l
            # make testex19
            /usr/bin/mpiexec -n 1 --oversubscribe ./ex19 -da_refine 3 -pc_type mg -ksp_type fgmres
            cat output/ex19_1.testout
            popd
            cat /tmp/makepkg/petsc/src/petsc-3.21.0/arch-linux-c-opt/lib/petsc/conf/configure.log