name: PETSc with SuperLU_DIST, dependencies are from archlinuxcn repository

on:
  push:
    branches: [main]
    paths:
      - patches/*

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: addnab/docker-run-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ghcr.io
          image: ghcr.io/cpp-review-dune/introductory-review/aur:latest
          options: |
            -v ${{github.workspace}}:/work
          shell: bash
          run: |
            curl -s https://gitlab.com/dune-archiso/dune-archiso.gitlab.io/-/raw/main/templates/add_archlinuxcn.sh | bash
            sudo pacman -Syuq --needed --noconfirm >/dev/null 2>&1
            # TODO: inetutils
            # FIXME: Unable to find superlu_dist in default locations!
            # valgrind
            # sudo pacman -S fftw hypre metis parmetis suitesparse hdf5-openmpi scotch mumps --noconfirm
            sudo pacman -S superlu_dist --noconfirm
            yay -G aur/petsc
            cd petsc
            makepkg --noconfirm -s
            pushd /tmp/makepkg/petsc/src/petsc-3.20.3/src/snes/tutorials
            make testex19
            /usr/bin/mpiexec -n 1 --oversubscribe ./ex19 -da_grid_x 20 -da_grid_y 20 -pc_type lu -pc_factor_mat_solver_type superlu_dist
            cat output/ex19_superlu.out
            popd
            cat /tmp/makepkg/petsc/src/petsc-3.20.3/arch-linux-c-opt/lib/petsc/conf/configure.log